In [1]:
import sys
import pandas as pd

print(sys.executable)
print(pd.__version__)

/workspaces/mlops-zoomcamp/.venv/bin/python
3.0.6

In [4]:
import pandas as pd

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-01.parquet"

df = pd.read_parquet(url)

df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2021-01-01 00:15:56,2021-01-01 00:19:52,N,1.0,43,151,1.0,1.01,5.5,0.5,0.5,0.00,0.0,None,0.3,6.80,2.0,1.0,0.00
1,2,2021-01-01 00:25:59,2021-01-01 00:34:44,N,1.0,166,239,1.0,2.53,10.0,0.5,0.5,2.81,0.0,None,0.3,16.86,1.0,1.0,2.75
2,2,2021-01-01 00:45:57,2021-01-01 00:51:55,N,1.0,41,42,1.0,1.12,6.0,0.5,0.5,1.00,0.0,None,0.3,8.30,1.0,1.0,0.00
3,2,2020-12-31 23:57:51,2021-01-01 00:04:56,N,1.0,168,75,1.0,1.99,8.0,0.5,0.5,0.00,0.0,None,0.3,9.30,2.0,1.0,0.00
4,2,2021-01-01 00:16:36,2021-01-01 00:16:40,N,2.0,265,265,3.0,0.00,-52.0,0.0,-0.5,0.00,0.0,None,-0.3,-52.80,3.0,1.0,0.00

In [5]:
print("Rows and columns:", df.shape)
df.info()

Rows and columns: (76518, 20)
<class 'pandas.DataFrame'>
RangeIndex: 76518 entries, 0 to 76517
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               76518 non-null  int64
 1   lpep_pickup_datetime   76518 non-null  datetime64[us]
 2   lpep_dropoff_datetime  76518 non-null  datetime64[us]
 3   store_and_fwd_flag     40471 non-null  str
 4   RatecodeID             40471 non-null  float64
 5   PULocationID           76518 non-null  int64
 6   DOLocationID           76518 non-null  int64
 7   passenger_count        40471 non-null  float64
 8   trip_distance          76518 non-null  float64
 9   fare_amount            76518 non-null  float64
 10  extra                  76518 non-null  float64
 11  mta_tax                76518 non-null  float64
 12  tip_amount             76518 non-null  float64
 13  tolls_amount           76518 non-null  float64
 14  ehail_fee              0 non-null      object
 15  improvement_surcharge  76518 non-null  float64
 16  total_amount           76518 non-null  float64
 17  payment_type           40471 non-null  float64
 18  trip_type              40471 non-null  float64
 19  congestion_surcharge   40471 non-null  float64
dtypes: datetime64[us](2), float64(13), int64(3), object(1), str(1)
memory usage: 11.7+ MB

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76518 entries, 0 to 76517
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               76518 non-null  int64
 1   lpep_pickup_datetime   76518 non-null  datetime64[us]
 2   lpep_dropoff_datetime  76518 non-null  datetime64[us]
 3   store_and_fwd_flag     40471 non-null  str
 4   RatecodeID             40471 non-null  float64
 5   PULocationID           76518 non-null  int64
 6   DOLocationID           76518 non-null  int64
 7   passenger_count        40471 non-null  float64
 8   trip_distance          76518 non-null  float64
 9   fare_amount            76518 non-null  float64
 10  extra                  76518 non-null  float64
 11  mta_tax                76518 non-null  float64
 12  tip_amount             76518 non-null  float64
 13  tolls_amount           76518 non-null  float64
 14  ehail_fee              0 non-null      object
 15  improvement_surcharge  76518 non-null  float64
 16  total_amount           76518 non-null  float64
 17  payment_type           40471 non-null  float64
 18  trip_type              40471 non-null  float64
 19  congestion_surcharge   40471 non-null  float64
dtypes: datetime64[us](2), float64(13), int64(3), object(1), str(1)
memory usage: 11.7+ MB

In [10]:
print(df.shape)

(76518, 20)

In [11]:
df["duration"] = (
    df["lpep_dropoff_datetime"] - df["lpep_pickup_datetime"]
).dt.total_seconds() / 60

df[[
    "lpep_pickup_datetime",
    "lpep_dropoff_datetime",
    "duration"
]].head()

  lpep_pickup_datetime lpep_dropoff_datetime  duration
0  2021-01-01 00:15:56   2021-01-01 00:19:52  3.933333
1  2021-01-01 00:25:59   2021-01-01 00:34:44  8.750000
2  2021-01-01 00:45:57   2021-01-01 00:51:55  5.966667
3  2020-12-31 23:57:51   2021-01-01 00:04:56  7.083333
4  2021-01-01 00:16:36   2021-01-01 00:16:40  0.066667

In [12]:
df["duration"].describe()

count    76518.000000
mean        19.927896
std         59.338594
min          0.000000
25%          8.000000
50%         13.883333
75%         23.000000
max       1439.600000
Name: duration, dtype: float64

In [13]:
df_clean = df.loc[
    (df["duration"] >= 1) & (df["duration"] <= 60)
].copy()

print("Original trips:", len(df))
print("Trips kept:", len(df_clean))
print("Trips removed:", len(df) - len(df_clean))

df_clean["duration"].describe()

Original trips: 76518
Trips kept: 73908
Trips removed: 2610

count    73908.000000
mean        16.852578
std         11.563163
min          1.000000
25%          8.050000
50%         14.000000
75%         22.633333
max         60.000000
Name: duration, dtype: float64